name: openhie-project
description: added description
# credentials:
# globals:
workflows:
  OpenHIE-Workflow:
    name: OpenHIE Workflow
    jobs:
      Notify-CHW-taylor-failed:
        name: Notify CHW testing
        adaptor: '@openfn/language-http@latest'
        enabled: true
        # credential:
        # globals:
        body: |
          fn(state => state);
          
      renaming-from-the-server:
        name: renaming from the server
        adaptor: '@openfn/language-http@latest'
        enabled: true
        # credential:
        # globals:
        body: |
          fn(state => state);
          
      Transform-data-to-FHIR-standard:
        name: Transform data to FHIR standard
        adaptor: '@openfn/language-http@latest'
        enabled: true
        # credential:
        # globals:
        body: |
          fn(state => state);
          
      Notify-CHW-upload-successful:
        name: Notify CHW upload successful
        adaptor: '@openfn/language-http@latest'
        enabled: true
        # credential:
        # globals:
        body: |
          fn(state => state);
          
    triggers:
      webhook:
        type: webhook
    edges:
      webhook->Transform-data-to-FHIR-standard:
        source_trigger: webhook
        target_job: Transform-data-to-FHIR-standard
        condition: always
      Transform-data-to-FHIR-standard->renaming-from-the-server:
        source_job: Transform-data-to-FHIR-standard
        target_job: renaming-from-the-server
        condition: on_job_success
      renaming-from-the-server->Notify-CHW-upload-successful:
        source_job: renaming-from-the-server
        target_job: Notify-CHW-upload-successful
        condition: on_job_success
      renaming-from-the-server->Notify-CHW-taylor-failed:
        source_job: renaming-from-the-server
        target_job: Notify-CHW-taylor-failed
        condition: on_job_failure