name: openhie-project
# description:
# credentials:
# globals:
workflows:
  OpenHIE-Workflow:
    name: OpenHIE Workflow
    jobs:
      Done-stuff-data-to-FHIR-standard:
        name: Done stuff data to FHIR standard
        adaptor: '@openfn/language-http@latest'
        # credential:
        # globals:
        body: |
          fn(state => state);
          
      Send-to-OpenHIM-to-route-to-SHR:
        name: Send to OpenHIM to route to SHR
        adaptor: '@openfn/language-http@latest'
        # credential:
        # globals:
        body: |
          fn(state => state);
          fn(x => {
            console.log("hi there!")
            return x;
          })
      Notify-CHW-upload-successful:
        name: Notify CHW upload successful
        adaptor: '@openfn/language-http@latest'
        # credential:
        # globals:
        body: |
          fn(state => state);
          
      Notify-CHW-upload-failed:
        name: Notify CHW upload failed
        adaptor: '@openfn/language-http@latest'
        # credential:
        # globals:
        body: |
          fn(state => state);
          
    triggers:
      webhook:
        type: webhook
        enabled: true
    edges:
      webhook->Done-stuff-data-to-FHIR-standard:
        source_trigger: webhook
        target_job: Done-stuff-data-to-FHIR-standard
        condition_type: always
        enabled: true
      Done-stuff-data-to-FHIR-standard->Send-to-OpenHIM-to-route-to-SHR:
        source_job: Done-stuff-data-to-FHIR-standard
        target_job: Send-to-OpenHIM-to-route-to-SHR
        condition_type: on_job_success
        enabled: true
      Send-to-OpenHIM-to-route-to-SHR->Notify-CHW-upload-successful:
        source_job: Send-to-OpenHIM-to-route-to-SHR
        target_job: Notify-CHW-upload-successful
        condition_type: on_job_success
        enabled: true
      Send-to-OpenHIM-to-route-to-SHR->Notify-CHW-upload-failed:
        source_job: Send-to-OpenHIM-to-route-to-SHR
        target_job: Notify-CHW-upload-failed
        condition_type: on_job_failure
        enabled: true