name: openhie-project
description: added description
# credentials:
# globals:
workflows:
  OpenHIE-Workflow:
    name: OpenHIE Workflow
    jobs:
      Send-to-OpenHIM-to-route-to-Taylor:
        name: try renaming a job
        adaptor: '@openfn/language-http@latest'
        enabled: true
        # credential:
        # globals:
        body: |
          fn(state => state);
          
      Notify-CHW-taylor-failed:
        name: Notify CHW taylor failed
        adaptor: '@openfn/language-http@latest'
        enabled: true
        # credential:
        # globals:
        body: |
          fn(state => state);
          
      Transform-data-to-FHIR-standard:
        name: Transform data to FHIR standard
        adaptor: '@openfn/language-http@latest'
        enabled: true
        # credential:
        # globals:
        body: |
          fn(state => state);
          
      Notify-CHW-upload-successful:
        name: Notify CHW upload successful
        adaptor: '@openfn/language-http@latest'
        enabled: true
        # credential:
        # globals:
        body: |
          fn(state => state);
          
    triggers:
      webhook:
        type: webhook
    edges:
      webhook->Transform-data-to-FHIR-standard:
        source_trigger: webhook
        target_job: Transform-data-to-FHIR-standard
        condition: always
      Transform-data-to-FHIR-standard->Send-to-OpenHIM-to-route-to-Taylor:
        source_job: Transform-data-to-FHIR-standard
        target_job: Send-to-OpenHIM-to-route-to-Taylor
        condition: on_job_success
      Send-to-OpenHIM-to-route-to-Taylor->Notify-CHW-upload-successful:
        source_job: Send-to-OpenHIM-to-route-to-Taylor
        target_job: Notify-CHW-upload-successful
        condition: on_job_success
      Send-to-OpenHIM-to-route-to-Taylor->Notify-CHW-taylor-failed:
        source_job: Send-to-OpenHIM-to-route-to-Taylor
        target_job: Notify-CHW-taylor-failed
        condition: on_job_failure
