on: [repository_dispatch]

jobs:
  pull_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: A job to pull changes from Lightning
    steps:
      - name: Attempt Release 1
        uses: zacck/test-pull-action@0.0.4
        with: 
          secret_input: ${{ secrets.OPENFN_API_KEY }}
          project_id_input: ${{ secrets.OPENFN_PROJECT_ID }}
          commit_message_input: ${{ github.event.client_payload.message }}
